# Generated by Django 4.2.4 on 2023-09-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accident_index", models.IntegerField()),
                ("x", models.DecimalField(db_index=True, decimal_places=16, max_digits=20)),
                ("y", models.DecimalField(db_index=True, decimal_places=16, max_digits=20)),
                ("charged_num", models.IntegerField(null=True)),
                ("bac", models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ("was_drug_tested_num", models.IntegerField(null=True)),
                ("drug_test_result_num", models.IntegerField(null=True)),
                ("driver_condition_num", models.IntegerField(null=True)),
                ("vision_obscured", models.IntegerField(null=True)),
                ("contributing_circumstaces_1_num", models.IntegerField(null=True)),
                ("contributing_circumstaces_2_num", models.IntegerField(null=True)),
                ("vehicle_type_num", models.IntegerField(null=True)),
                ("vehicle_year", models.IntegerField(null=True)),
                ("vehicle_make", models.CharField(db_index=True, max_length=80, null=True)),
                ("vehicle_model", models.CharField(db_index=True, max_length=80, null=True)),
                ("occupants", models.IntegerField(null=True)),
                ("vehicle_action_num", models.IntegerField(null=True)),
                ("sequence_of_events_1_num", models.IntegerField(null=True)),
                ("sequence_of_events_2_num", models.IntegerField(null=True)),
                ("sequence_of_events_3_num", models.IntegerField(null=True)),
                ("sequence_of_events_4_num", models.IntegerField(null=True)),
                ("most_harmful_event_num", models.IntegerField(null=True)),
                ("speed_limit", models.IntegerField(null=True)),
                ("traffic_control_num", models.IntegerField(null=True)),
                ("fixed_object_struck_num", models.IntegerField(null=True)),
                ("most_damage_area_num", models.IntegerField(null=True)),
                ("extent_of_damage_num", models.IntegerField(null=True)),
                ("crash_severity", models.IntegerField(null=True)),
                ("major_cause_num", models.IntegerField(null=True)),
                ("surface_conditions_num", models.IntegerField(null=True)),
                ("road_type_num", models.IntegerField(null=True)),
                ("total_fatalities", models.IntegerField(null=True)),
                ("crash_year", models.IntegerField(null=True)),
                ("crash_datetime", models.DateTimeField(null=True, blank=True)),
                ("cluster_id", models.IntegerField(null=True)),
            ],
        ),
    ]
