# Generated by Django 4.2.4 on 2023-09-13 01:51

from django.db import migrations

def attach_accidents_to_clusters(apps, schema_editor):
    '''
    We can't import the Accident model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Accident = apps.get_model('portal_app', 'Accident')
    Intersection = apps.get_model('portal_app', 'Intersection')
    for accident in Accident.objects.all():
        accident.intersection_id = Intersection.objects.get(cluster_id=accident.cluster_id)
        accident.save()


class Migration(migrations.Migration):

    dependencies = [
        ("portal_app", "0003_accident_intersection"),
    ]

    operations = [migrations.RunPython(attach_accidents_to_clusters)]
